# Copyright 2026 Phillip Cloud
# Licensed under the Apache License, Version 2.0

version: 2

builds:
  - main: ./cmd/micasa
    binary: micasa
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "micasa_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true

release:
  mode: keep-existing
